---
- name: Jump host üzərində ilkin əməliyyatlar
  hosts: jump
  gather_facts: false
  tasks:
    - name: "Jump host test: hostname"
      ansible.builtin.shell: hostname
      register: jump_hostname
    - debug: var=jump_hostname.stdout

- name: Daxili VM üzərində əməliyyatlar (jump host vasitəsilə)
  hosts: internal
  gather_facts: false
  tasks:
    - name: "Daxili VM test: hostname"
      ansible.builtin.shell: hostname
      register: internal_hostname
    - debug: var=internal_hostname.stdout
