name: Ansible Deploy

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Get Sonarqube Public IP
        id: get_ip
        run: |
          echo "SONARQUBE_IP=$(terraform -chdir=terraform output -raw sonarqube_vm_public_ip)" >> $GITHUB_ENV

      - name: Render dynamic inventory
        run: |
          export SONARQUBE_IP=${{ env.SONARQUBE_IP }}
          export SONARQUBE_VM_PASSWORD=${{ secrets.SONARQUBE_VM_PASSWORD }}
          export VM_PASSWORD=${{ secrets.VM_PASSWORD }}
          envsubst < ansible/dynamic_inventory.ini.j2 > ansible/dynamic_inventory.ini

      - name: Run Ansible Playbook (bridge)
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i ansible/dynamic_inventory.ini ansible/playbook_bridge.yml
