name: Terraform – Burger Builder Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action to run"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  call-terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      action: ${{ github.event.inputs.action }}
    secrets: inherit